### ISSUE TITLE
Converting to boolean

### ISSUE THREAD

**Issue by FrankReh** [HL7/FHIRPath#6]
Will there be a toBoolean() function defined or can the section about converting to boolean be expanded?

It might help clarify how various cases should be handled. It seems partially implied and partially explicitly stated that trying to get a Boolean (which is a singleton) from a collection can result in one of four cases:
a truth value, a false value, an empty collection, or an error being raised.

Can you state something like this?

Implicit conversion to Boolean from a collection of multiple items raises an error.
Implicit conversion to Boolean from an empty collection returns an empty collection.
Implicit conversion to Boolean from a single item collection can result in one of the four cases mentioned above already, true, false, empty collection or error raised as follows:

If singleton is:

- true or false already, return the true or false
- an Integer, return true for 1, false for 0, raise error for any other value
- a Decimal, return true for 1.0, false for 0.0, raise error for any other value
- a String, once converted to lower case:
  - return true for y, yes, t, true or 1
  - return false for n, no, f, false, or 0
  - raise error for other string values
- any Time, DateTime or Quantity, raise an error

- if singleton is a collection itself (assuming Collections of Collections are allowed)
  - apply the above rules recursively.

The spec also could be clearer if the functions that return value Boolean could be distinguished between the four cases somehow consistently. Which functions return only true or false. Which return true or false or empty. Which return true or false or raise an error. Which return true or false or empty or raise an error. Maybe don't just use the word Boolean as the return in the function signature? One form of nomenclature could be
true|false
true|false|empty
true|false|error
true|false|empty|error

**Comment by brynrhodes** [comment]
Conversion functions in general, and [`toBoolean`](http://hl7.org/fhirpath/#boolean-conversion-functions) in particular have been improved in the latest release of the specification. If these changes do not address this issue, feel free to re-open or submit a new issue. Note that since FHIRPath is an HL7 specification, any changes to the specification should be requested through the [HL7 Jira](https://jira.hl7.org/projects/FHIR/issues). Be sure to indicate FHIRPath as the specification when submitting change requests through the HL7 Jira.
